name: build

on:
  push:
    branches: master
  schedule:
    # Run daily
    - cron:  '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx create --driver-opt image=moby/buildkit:master --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'
          docker buildx use insecure-builder
          docker buildx build \
            --progress=plain \
            --allow security.insecure \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag bredos/bredos:latest \
            --file Dockerfile \
            --push .