name: build

on:
  push:
    branches: main
  schedule:
    # Run daily
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            buildkitd-flags: '--allow-insecure-entitlement security.insecure'


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            platforms: linux/amd64,linux/arm64v8,linux/arm32v7
            push: true
            tags: bredos/bredos:latest
            file: Dockerfile
            allow: security.insecure
